name: CI

on: [push, pull_request]

jobs:
  Host-Freestanding:
    strategy:
      matrix:
        operating-system: [macos-latest]
        ocaml-version: [4.13.1]
    runs-on: ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-version }}
        dune-cache: true
        opam-local-packages: |
          !gmp.opam
    - name: Add mirage-dev repository
      run: opam repo add mirage-dev git+https://github.com/mirage/mirage-dev.git#master
    - name: Compiling example project
      run: opam exec -- dune build @install
    - name: Running tests
      run: opam exec -- dune runtest
